export enum RESOURCE {
  ADULTO = 'ADULTO',
  PROTAGONISTA = 'PROTAGONISTA',
  RESPONSABLE = 'RESPONSABLE',
  PAGO = 'PAGO',
  CONCEPTO_PAGO = 'CONCEPTO_PAGO',
  METODO_PAGO = 'METODO_PAGO',
  CUENTA_DINERO = 'CUENTA_DINERO',
  EVENTO = 'EVENTO',
  TIPO_EVENTO = 'TIPO_EVENTO',
  USER = 'USER',
}

export enum ACTION {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  MANAGE = 'MANAGE',
}

export interface Permission {
  resource: RESOURCE;
  action: ACTION;
}
